//created by Raül López
import {Meteor} from 'meteor/meteor';
import {Posicions} from '../../api/old/collections/posicions.js';
export default function () {
  if (Posicions.find({}).count() === 0) {
      Posicions.insert({'zona':'EEII - Peus','os':'Dits del peu','posicio':'AP','centratge':'Falange proximal'});
      Posicions.insert({'zona':'EEII - Peus','os':'Dits del peu','posicio':'Obliqua','centratge':'Falange proximal'});
      Posicions.insert({'zona':'EEII - Peus','os':'Peus','posicio':'AP','centratge':'Meitat del tercer metatarsià'});
      Posicions.insert({'zona':'EEII - Peus','os':'Peus','posicio':'Perfil','centratge':'Meitat del peu'});
      Posicions.insert({'zona':'EEII - Peus','os':'Peus','posicio':'Obliqua interna','centratge':'Meitat del tercer metatarsià'});
      Posicions.insert({'zona':'EEII - Peus','os':'Peus en càrrega','posicio':'AP','centratge':'Meitat dels dos peus'});
      Posicions.insert({'zona':'EEII - Peus','os':'Peus en càrrega','posicio':'Perfil','centratge':'Meitat del pont'});
      Posicions.insert({'zona':'EEII - Peus','os':'Sesamoideos','posicio':'Axial','centratge':'Meitat primera i segona art. Metatarsofalàngica'});
      Posicions.insert({'zona':'EEII - Peus','os':'Calcani','posicio':'Axial','centratge':'Meitat calcani'});
      Posicions.insert({'zona':'EEII - Peus','os':'Calcani','posicio':'Lateral','centratge':'Meitat calcani'});
      Posicions.insert({'zona':'EEII - Peus','os':'Turmell','posicio':'AP','centratge':'Mal·lèols'});
      Posicions.insert({'zona':'EEII - Peus','os':'Turmell','posicio':'Lateral','centratge':'Mal·lèol tibial'});
      Posicions.insert({'zona':'EEII - Peus','os':'Turmell','posicio':'Obliqua interna','centratge':'Mal·lèol peroneal '});
      Posicions.insert({'zona':'EEII - Peus','os':'Turmell','posicio':'Obliqua externa','centratge':'Mal·lèol tibial'});
      Posicions.insert({'zona':'EEII - Peus','os':'Turmell','posicio':'Varo','centratge':'Mig turmell'});
      Posicions.insert({'zona':'EEII - Peus','os':'Turmell','posicio':'Valgo','centratge':'Mig turmell'});
      Posicions.insert({'zona':'EEII - Peus','os':'Turmell','posicio':'Subastragalina','centratge':'Articulació subastragalina'});
      Posicions.insert({'zona':'EEII - Cama inferior','os':'Tibia i peroné','posicio':'AP','centratge':'Diàfisi tibial'});
      Posicions.insert({'zona':'EEII - Cama inferior','os':'Tibia i peroné','posicio':'Lateral','centratge':'Diàfisi tibial'});
      Posicions.insert({'zona':'EEII - Cama inferior','os':'Tibia i peroné','posicio':'Obliqua externa','centratge':'Diàfisi tibial'});
      Posicions.insert({'zona':'EEII - Cama inferior','os':'Tibia i peroné','posicio':'Obliqua interna','centratge':'Diàfisi tibial'});
      Posicions.insert({'zona':'EEII - Genoll','os':'Genoll','posicio':'AP','centratge':'Pol inferior ròtula'});
      Posicions.insert({'zona':'EEII - Genoll','os':'Genoll','posicio':'Perfil','centratge':'Pol inferior ròtula'});
      Posicions.insert({'zona':'EEII - Genoll','os':'Genoll','posicio':'Obliqua externa','centratge':'Pol inferior ròtula'});
      Posicions.insert({'zona':'EEII - Genoll','os':'Genoll','posicio':'Obliqua interna','centratge':'Pol inferior ròtula'});
      Posicions.insert({'zona':'EEII - Genoll','os':'Genoll','posicio':'Fick','centratge':'Forat poplítia'});
      Posicions.insert({'zona':'EEII - Genoll','os':'Genoll en càrrega','posicio':'AP','centratge':'Entre els dos genolls'});
      Posicions.insert({'zona':'EEII - Genoll','os':'Genoll en càrrega','posicio':'Perfil','centratge':'Còndils femorals'});
      Posicions.insert({'zona':'EEII - Genoll','os':'Ròtula','posicio':'Axials','centratge':'Pol inferior ròtula'});
      Posicions.insert({'zona':'EEII - Fèmur','os':'Fèmur','posicio':'AP','centratge':'Diàfisi femoral'});
      Posicions.insert({'zona':'EEII - Fèmur','os':'Fèmur','posicio':'Lateral','centratge':'Diàfisi femoral'});
      Posicions.insert({'zona':'Cintura pèlvica','os':'Maluc','posicio':'Front','centratge':'Angonal'});
      Posicions.insert({'zona':'Cintura pèlvica','os':'Maluc','posicio':'Axial','centratge':'Angonal'});
      Posicions.insert({'zona':'Cintura pèlvica','os':'Maluc','posicio':'Alar','centratge':'Angonal'});
      Posicions.insert({'zona':'Cintura pèlvica','os':'Forat obturatriu','posicio':'AP','centratge':'Angonal'});
      Posicions.insert({'zona':'Cintura pèlvica','os':'Pelvis','posicio':'AP','centratge':'Meitat zona pèlvica'});
      Posicions.insert({'zona':'Cintura pèlvica','os':'Pelvis','posicio':'Inlet','centratge':'Meitat zona pèlvica'});
      Posicions.insert({'zona':'Cintura pèlvica','os':'Pelvis','posicio':'Outlet','centratge':'Meitat zona pèlvica'});
      Posicions.insert({'zona':'Columna','os':'Sacre i còxis','posicio':'AP','centratge':'3 dits sota crestes il·líaques'});
      Posicions.insert({'zona':'Columna','os':'Sacre i còxis','posicio':'Perfil','centratge':'Crestes il·líaques'});
      Posicions.insert({'zona':'Columna','os':'Lumbar','posicio':'AP','centratge':'Crestes il·líaques'});
      Posicions.insert({'zona':'Columna','os':'Lumbar','posicio':'Perfil','centratge':'Crestes il·líaques'});
      Posicions.insert({'zona':'Columna','os':'Lumbar','posicio':'Obliqua','centratge':'Crestes il·líaques'});
      Posicions.insert({'zona':'Columna','os':'Lumbar','posicio':'Funcional','centratge':'Crestes il·líaques'});
      Posicions.insert({'zona':'Columna','os':'Dorsal','posicio':'AP','centratge':'Línia mamària'});
      Posicions.insert({'zona':'Columna','os':'Dorsal','posicio':'Perfil','centratge':'Línia axil·lomamària'});
      Posicions.insert({'zona':'Columna','os':'Dorsal','posicio':'Obliqua','centratge':'Línia axil·lomamària'});
      Posicions.insert({'zona':'Columna','os':'Dorsal','posicio':'Funcional','centratge':'Línia axil·lomamària'});
      Posicions.insert({'zona':'Columna','os':'Cervical','posicio':'AP','centratge':'Nou'});
      Posicions.insert({'zona':'Columna','os':'Cervical','posicio':'Perfil','centratge':'Nou'});
      Posicions.insert({'zona':'Columna','os':'Cervical','posicio':'Obliqua','centratge':'Nou'});
      Posicions.insert({'zona':'Columna','os':'Cervical','posicio':'Funcional','centratge':'Nou'});
      Posicions.insert({'zona':'Columna','os':'Cervical','posicio':'Transoral','centratge':'Meitat de la boca'});
      Posicions.insert({'zona':'Abdomen','os':'Abdomen','posicio':'Decúbit supí','centratge':'Línia mitja sagital'});
      Posicions.insert({'zona':'Abdomen','os':'Abdomen','posicio':'Bipedestació','centratge':'Línia mitja sagital'});
      Posicions.insert({'zona':'Abdomen','os':'Abdomen','posicio':'Decúbit lateral','centratge':'Crestes il·líaques'});
      Posicions.insert({'zona':'Caixa toràcica','os':'Tórax','posicio':'PA','centratge':'Estèrnum'});
      Posicions.insert({'zona':'Caixa toràcica','os':'Tórax','posicio':'AP','centratge':'Estèrnum'});
      Posicions.insert({'zona':'Caixa toràcica','os':'Tórax','posicio':'Perfil','centratge':'Línia axil·lomamària'});
      Posicions.insert({'zona':'Caixa toràcica','os':'Tórax','posicio':'Lordòtica','centratge':'Estèrnum'});
      Posicions.insert({'zona':'Caixa toràcica','os':'Tórax','posicio':'Decúbit lateral','centratge':'Estèrnum'});
      Posicions.insert({'zona':'Caixa toràcica','os':'Costelles','posicio':'AP','centratge':'Meitat del pit'});
      Posicions.insert({'zona':'Caixa toràcica','os':'Costelles','posicio':'Obliqua','centratge':'Línia axil·lomamària'});
      Posicions.insert({'zona':'Caixa toràcica','os':'Estèrnum','posicio':'Perfil','centratge':'Línia axil·lomamària i 4 dits anterior'});
      Posicions.insert({'zona':'Cintura escapular','os':'Clavicula','posicio':'Front','centratge':'Mig clavícula'});
      Posicions.insert({'zona':'Cintura escapular','os':'Clavicula','posicio':'Desenfilada','centratge':'Mig clavícula'});
      Posicions.insert({'zona':'Cintura escapular','os':'Escàpula','posicio':'AP','centratge':'Mig escàpula'});
      Posicions.insert({'zona':'Cintura escapular','os':'Escàpula','posicio':'Perfil','centratge':'Mig escàpula'});
      Posicions.insert({'zona':'Cintura escapular','os':'Acromio-clavicular','posicio':'AP','centratge':'Art. Acromio-clavicular'});
      Posicions.insert({'zona':'EESS - Muscle','os':'Muscle','posicio':'Axilar','centratge':'Art. Acromio-clavicular'});
      Posicions.insert({'zona':'EESS - Muscle','os':'Muscle','posicio':'Axial','centratge':'Aixella'});
      Posicions.insert({'zona':'EESS - Muscle','os':'Muscle','posicio':'Outlet','centratge':'Fosa supraespinosa'});
      Posicions.insert({'zona':'EESS - Muscle','os':'Muscle','posicio':'Rotació neutra','centratge':'Fosa glenoidea'});
      Posicions.insert({'zona':'EESS - Muscle','os':'Muscle','posicio':'Rotació interna','centratge':'Fosa glenoidea'});
      Posicions.insert({'zona':'EESS - Muscle','os':'Muscle','posicio':'Rotació externa','centratge':'Fosa glenoidea'});
      Posicions.insert({'zona':'EESS - Húmer','os':'Húmer','posicio':'AP','centratge':'Diàfisi humeral'});
      Posicions.insert({'zona':'EESS - Húmer','os':'Húmer','posicio':'Transtoràcica','centratge':'8 dits sota axil·la'});
      Posicions.insert({'zona':'EESS - Húmer','os':'Húmer','posicio':'Perfil','centratge':'Diàfisi humeral'});
      Posicions.insert({'zona':'EESS - Colze','os':'Colze','posicio':'AP','centratge':'Flexora colze'});
      Posicions.insert({'zona':'EESS - Colze','os':'Colze','posicio':'Obliqua interna','centratge':'Mig colze'});
      Posicions.insert({'zona':'EESS - Colze','os':'Colze','posicio':'Obliqua externa','centratge':'Mig colze'});
      Posicions.insert({'zona':'EESS - Colze','os':'Colze','posicio':'Perfil','centratge':'Epicòndil'});
      Posicions.insert({'zona':'EESS - Avantbraç','os':'Avantbraç','posicio':'AP','centratge':'Mig avantbraç'});
      Posicions.insert({'zona':'EESS - Avantbraç','os':'Avantbraç','posicio':'Perfil','centratge':'Mig avantbraç'});
      Posicions.insert({'zona':'EESS - Canell','os':'Canell','posicio':'Gaynor Hart','centratge':'Flexora canell'});
      Posicions.insert({'zona':'EESS - Canell','os':'Canell','posicio':'Mètode Labarta','centratge':'Estiloides radial'});
      Posicions.insert({'zona':'EESS - Canell','os':'Canell','posicio':'Sneck','centratge':'Estiloides radial'});
      Posicions.insert({'zona':'EESS - Canell','os':'Canell','posicio':'Obliqua externa','centratge':'Mig carp'});
      Posicions.insert({'zona':'EESS - Canell','os':'Canell','posicio':'Obliqua interna','centratge':'Mig carp'});
      Posicions.insert({'zona':'EESS - Canell','os':'Canell','posicio':'Funcional flexió palmar','centratge':'Estiloides radial'});
      Posicions.insert({'zona':'EESS - Canell','os':'Canell','posicio':'Funcional flexió dorsal','centratge':'Estiloides radial'});
      Posicions.insert({'zona':'EESS - Canell','os':'Canell','posicio':'Funcional desviació cubital','centratge':'Mig carp'});
      Posicions.insert({'zona':'EESS - Canell','os':'Canell','posicio':'Funcional desviació radial','centratge':'Mig carp'});
      Posicions.insert({'zona':'EESS - Canell','os':'Canell','posicio':'PA','centratge':'Mig carp'});
      Posicions.insert({'zona':'EESS - Canell','os':'Canell','posicio':'Perfil','centratge':'Estiloides radial'});
      Posicions.insert({'zona':'EESS - Mà','os':'Mà','posicio':'Norgaard','centratge':'Mig mà'});
      Posicions.insert({'zona':'EESS - Mà','os':'Mà','posicio':'Perfil','centratge':'Mig mà'});
      Posicions.insert({'zona':'EESS - Mà','os':'Mà','posicio':'Obliqua','centratge':'Mig mà'});
      Posicions.insert({'zona':'EESS - Mà','os':'Mà','posicio':'PA','centratge':'Mig mà'});
      Posicions.insert({'zona':'EESS - Dits','os':'Dits','posicio':'Perfil','centratge':'Mig dits'});
      Posicions.insert({'zona':'EESS - Dits','os':'Dits','posicio':'PA','centratge':'Mig dits'});
      Posicions.insert({'zona':'Crani','os':'Crani','posicio':'PA','centratge':'Protuberància occipital ext.'});
      Posicions.insert({'zona':'Crani','os':'Crani','posicio':'Perfil','centratge':'2cm davant CAE i 2cm per damunt'});
      Posicions.insert({'zona':'Crani','os':'Crani','posicio':'Towne','centratge':'Entrada cabell'});
      Posicions.insert({'zona':'Crani','os':'Crani','posicio':'Hirtz','centratge':'Sota mentó'});
      Posicions.insert({'zona':'Crani','os':'Òrbites','posicio':'PA','centratge':'4 dits sobre protuberància occipital ext.'});
      Posicions.insert({'zona':'Crani','os':'Òrbites','posicio':'Rhese PA','centratge':'Òrbita'});
      Posicions.insert({'zona':'Crani','os':'Ós zigomàtic','posicio':'Variant Hirtz','centratge':'Arc zigomàtic'});
      Posicions.insert({'zona':'Crani','os':'Ossos propis','posicio':'PA','centratge':'Protuberància occipital ext.'});
      Posicions.insert({'zona':'Crani','os':'Ossos propis','posicio':'Perfil','centratge':'Mig nas'});
      Posicions.insert({'zona':'Crani','os':'Sins paranasals','posicio':'PA','centratge':'Protuberància cranial'});
      Posicions.insert({'zona':'Crani','os':'Càvum','posicio':'Perfil','centratge':'Sota orella'});
      Posicions.insert({'zona':'Crani','os':'Maxil·lar inferior','posicio':'PA','centratge':'Zona bucal'});
      Posicions.insert({'zona':'Crani','os':'Maxil·lar ','posicio':'Perfil','centratge':'2cm davant CAE i 2cm per damunt'});
      Posicions.insert({'zona':'Crani','os':'ATM','posicio':'Obliqua','centratge':'2cm davant CAE i 2cm per damunt'});
      Posicions.insert({'zona':'Crani','os':'ATM tancada','posicio':'Perfil','centratge':'2cm davant CAE i 2cm per damunt'});
      Posicions.insert({'zona':'Crani','os':'ATM oberta','posicio':'Perfil','centratge':'2cm davant CAE i 2cm per damunt'});
      Posicions.insert({'zona':'Crani','os':'Ortopantomografia','posicio':'','centratge':'Automàtic'});
      Posicions.insert({'zona':'Crani','os':'Telemetria ','posicio':'','centratge':'Automàtic'});
  }
};
